version: '3.5'
services:
  web:
    build: ./frontend
    container_name: md-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_GATEWAY_URL=http://localhost:4000/graphql
  mongo:
    image: mongo
    container_name: md-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  ad:
    build: ./server/micros/ad
    container_name: md-ad
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - DB_URL=mongodb://mongo:27017/test
      - AUTH_URL=http://auth:4002/graphql
    depends_on:
      - mongo
      - auth
    links:
      - mongo
      - auth
  auth:
    build: ./server/micros/auth
    container_name: md-auth
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - DB_URL=mongodb://mongo:27017/test
      - CLIENT_ID=minddenCodeTest
      - SIGNING_KID=M1nDd3Nc0D3t3St
    depends_on:
      - mongo
    links:
      - mongo
  gateway:
    build: ./server/micros/gateway
    container_name: md-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - AUTH_MICRO=http://auth:4002/graphql
      - AD_MICRO=http://ad:4001/graphql
      - SLEEP_LENGTH=10000
    depends_on:
      - mongo
      - ad
      - auth
    links:
      - mongo
      - ad
      - auth